name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      # Need to build the WASM before type-checking
      # otherwise we're missing code and tsc will fail
      - name: Build WASM
        run: pnpm build:wasm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate papi descriptors
        run: pnpm run papi:generate

      - name: Check formatting
        run: pnpm fmt-check

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm tsc -b --noEmit

      - name: Build
        run: pnpm build
